# Generated by Django 3.0.5 on 2020-04-05 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Заголовок: ')),
                ('slug', models.SlugField(unique=True)),
                ('img', models.ImageField(upload_to='static/img/posts/', verbose_name='Изображение: ')),
                ('fdesc', models.TextField(max_length=500, verbose_name='Краткое описание')),
                ('sdesc', models.TextField(verbose_name='Полное описание')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
